apiVersion: k8s.wasmcloud.dev/v1alpha1
kind: WasmCloudHostConfig
metadata:
  name: wasmcloud-host
spec:
  lattice: default
  version: "1.4.2"
  hostLabels:
    cluster-type: kind
  # registryCredentialsSecret: "regcred"
